theme: jekyll-theme-slate
title: Robust  Perception  For  Autonomous  Field  Robots  in  Challenging Environments
description: Proposed workshop for the 2021 International Conference on Robotics and Automation (ICRA)
